import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root Layout component that wraps the entire Next.js application.
 * It provides the global HTML structure, fonts, CSS variables, and the Redux Store provider.
 * 
 * @param {Object} props - Component props.
 * @param {React.ReactNode} props.children - The child components/pages to render inside the body.
 * @returns {React.ReactElement} The root HTML element.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased font-inter`}
    >
      <body className="min-h-full flex flex-col font-inter">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
